### ISSUE TITLE
Unable to find: /vendor/autoload.php

### ISSUE THREAD

**Issue by dotmat** [Clarify/clarify-php#10]
Hi, 
I've downloaded the library but am unable to find: /vendor/autoload.php
Am I missing something?

Thanks!

**Comment by caseysoftware** [comment]
From the root of the project, run composer:

```composer install```

and it should create the vendor folder and install the required libraries.

**Comment by dotmat** [comment]
Hi, 
Is there a way I can do it without composer?
Thanks!

**Comment by caseysoftware** [comment]
I've been thinking on this one and I think you could but it's not easy. You'd have to have the include path for each and every one of our classes along with the dependency libraries. Guzzle is our main one but that's still a lot of classes and you'd have to update it if any of the libraries added a class.

Are you opposed to using Composer or just trying to skip it?
